server:
  port: 8082
spring:
  datasource:
    #    连接docker数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://172.19.0.2/CRM
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
logging:
  pattern:
#    console: "[%thread] %-5level %logger{36} - %msg%n"

