spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://mysql56:3306/CRM
  redis:
    database: 0
    host: myredis
    port: 6379