spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://mysql_g2:3306/CRM
  redis:
    database: 0
    host: redis_g2
    port: 6379