# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      master:
        url: jdbc:mysql://mysqlg21:3306/ry
        username: root
        password: 123456
  redis:
    database: 0
    host: rjredis
    port: 6380
