--  任务周期定义
DROP TABLE IF EXISTS TASK_CYCLE;
CREATE TABLE IF NOT EXISTS TASK_CYCLE
(
    TC_ID       BIGINT NOT NULL COMMENT '主键',
    TC_BEGIN    VARCHAR(32) COMMENT '起始日期',
    TC_END      VARCHAR(32) COMMENT '结束日期',
    TC_FID      CHAR(36) COMMENT '父节点',
    PRIMARY KEY (TC_ID)
) DEFAULT CHARSET = utf8mb4 COMMENT '任务周期定义';

-- 表格任务计划&总的列清单
DROP TABLE IF EXISTS TASK_REVIEW;
CREATE TABLE IF NOT EXISTS TASK_REVIEW
(
    TASK_REVIEW_ID              BIGINT NOT NULL COMMENT '主键',
    TC_ID                       BIGINT NOT NULL COMMENT '周期主键，关联任务周期定义表',
    SALE_ID                     CHAR(36) COMMENT '销售人员',
    TASK_REVIEW_STATE           VARCHAR(32) COMMENT '总结状态',
    TASK_REVIEW_DESC            TEXT COMMENT '总结说明',
    TASK_REVIEW_VISITS_TOTAL    INT COMMENT '拜访总数',
    TASK_REVIEW_STRANGE         INT COMMENT '陌生拜访总数',
    TASK_REVIEW_NEW_INTENCUST   INT COMMENT '新增意向用户',
    PRIMARY KEY (TASK_REVIEW_ID)
) DEFAULT CHARSET = utf8mb4 COMMENT '表格任务计划&总的列清单';

-- 我的任务细项
DROP TABLE IF EXISTS MY_TASKS;
CREATE TABLE IF NOT EXISTS MY_TASKS
(
    TASK_ID             BIGINT NOT NULL COMMENT '任务主键',
    ORG_ID              BIGINT NOT NULL COMMENT '潜在客户主键，关联潜在客户表',
    CUST_ID             BIGINT NOT NULL COMMENT '客户主键，客户管理的列清单',
    TASK_REVIEW_ID      BIGINT NOT NULL COMMENT '任务计划主键，关联任务计划&总的列清单',
    SALE_ID             CHAR(36) COMMENT '销售人员',
    TASK_FOLLOW_STATE   VARCHAR(32) COMMENT '跟进状态',
    TASK_CLASS          VARCHAR(32) COMMENT '任务类别',
    TASK_CREATE_TIME    VARCHAR(32) COMMENT '创建任务时间',
    TASK_FINISH_TIME    VARCHAR(32) COMMENT '任务完成时间',
    TASK_CUST_STATE     VARCHAR(32) COMMENT '客户状态',
    PRIMARY KEY (TASK_ID)
) DEFAULT CHARSET = utf8mb4 COMMENT '我的任务细项';

-- 系统用户表
DROP TABLE IF EXISTS SECURITY_USER;
CREATE TABLE IF NOT EXISTS SECURITY_USER
(
    USER_ID       BIGINT NOT NULL COMMENT '用户ID',
    USER_NAME     VARCHAR(32) COMMENT '姓名',
    USER_CODE     VARCHAR(32) COMMENT '用户编码',
    USER_PWD      VARCHAR(32) COMMENT '密码',
    USER_SEX      VARCHAR(1) COMMENT '性别',
    USER_DESC     VARCHAR(128) COMMENT '描述',
    USER_STATE    VARCHAR(32) COMMENT '状态',
    USER_MAIL     VARCHAR(64) COMMENT '邮箱',
    USER_SORT     INT COMMENT '排序',
    USER_PHONE    VARCHAR(64) COMMENT '手机',
    DISPLAY_COUNT INT COMMENT '显示个数',
    GRP_ID        BIGINT COMMENT '组织ID，关联SECURITY_GROUP',
    PRIMARY KEY (USER_ID)
) DEFAULT CHARSET = utf8mb4 comment '系统用户表';